# Define the name of the bridge and its docker image.
NAME = sklearn
IMAGE_NAME = bridge.sklearn

# Include all other necessary Makefiles.
ROOT = ./../../../
include $(ROOT)/scripts/python/integrate.Makefile
