fail_fast: false
default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        files: examples/python/bridges/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        files: examples/python/bridges/
        args: [
            "--py3-plus",
            "--py36-plus",
            "--py37-plus",
        ]

  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        files: examples/python/bridges/
        args: ["--line-length", "100"]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=775"]
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: examples/python/bridges/
        args: ["--max-line-length", "100"]
