# Define the name of the bridge and its docker image
NAME = climetlab
IMAGE_NAME = bridge.climetlab

# Include all other necessary Makefiles.
ROOT = ./../../../
include $(ROOT)/scripts/python/integrate.Makefile
