# Define the name of the bridge and its docker image
NAME = xarray
IMAGE_NAME = bridge.xarray

# Include all other necessary Makefiles.
ROOT = ./../../../../
include $(ROOT)/scripts/python/integrate.Makefile
