NAME = sklearn
ROOT_DIR=./../../../../
SCRIPTS_DIR=$(ROOT_DIR)scripts/
PYTHON_SCRIPTS_DIR=./../../scripts/
DOCKER_IMAGE_NAME=bridge.sklearn
DOCKER_FILE=$(PYTHON_SCRIPTS_DIR)Dockerfile.python_bridge
include $(PYTHON_SCRIPTS_DIR)Makefile.python_bridge
include $(SCRIPTS_DIR)Makefile.docker_single

