# Define the name of the bridge and its docker image
NAME = sklearn.simple
DOCKER_IMAGE_NAME=bridge.sklearn.simple

# Include all other necessary Makefiles.
PYTHON_SCRIPTS=./../../../scripts
include  $(PYTHON_SCRIPTS)/Makefile.integrate
