[tool.poetry]
name = "mantik-sklearn-bridge"
description = "Mantik bridge for sklearn"
version = "0.1.0"
authors = ["Mantik Team <info@mantik.ai>"]
homepage = "https://www.mantik.ai"

[tool.poetry.dependencies]
python = "~3.9"
mantik = { path = "./python_sdk", develop = true }
mnp = { path = "./mnppython", develop = true }
scikit-learn = "^0.24.2"
pandas = "1.3.2"
xarray = "0.19.0"
netCDF4 = "1.5.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry>=1.0.0"]

[tool.pytest.ini_options]
norecursedirs = "target"
