# Define the name of the bridge and its docker image
NAME = sklearn.production
DOCKER_IMAGE_NAME=bridge.sklearn.production

# Include all other necessary Makefiles.
PYTHON_SCRIPTS=./../../../scripts
include  $(PYTHON_SCRIPTS)/Makefile.integrate
