# Define the name of the bridge and its docker image
NAME = pandas
IMAGE_NAME = bridge.pandas

# Include all other necessary Makefiles.
ROOT = ./../../../../
include $(ROOT)/scripts/python/integrate.Makefile
